server.port: 8080

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/tomcatdb
    username: postgres
    password: password
    pool-size: 30

spring:
  security:
    filter:
      order: 10